[workspace]
resolver = "2"
members = [
    "error",
    "protocol",
    "rt",
    "schema",
    "types",
    "watcher",
]

[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.85"

[workspace.lints.clippy]
collapsible_if = "allow"

[workspace.dependencies]
anyhow = "1.0"
atoi = "2.0"
bitflags = "2.9"
bytes = "1"
futures = "0.3"
phf = { version = "0.12", default-features = false }
phf_codegen = "0.12"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
thiserror = "2"
tokio-stream = "0.1"
tokio-util = { version = "0.7", features = ["codec"] }
tokio = { version = "1.45", features = ["rt-multi-thread", "process", "io-util"] }
schemars = "1.0"
async-trait = "0.1.89"
notify = "8.2"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
