[package]
name = "journal-function"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[features]
allocative = ["dep:allocative"]


[dependencies]
async-stream = "0.3"
async-trait = { workspace = true }
futures = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
notify = { workspace = true }
foyer = { workspace = true }
parking_lot = { workspace = true, features = ["send_guard"] }
schemars = { workspace = true }
chrono = { version = "0.4", features = ["serde"] }
nix = { version = "0.30", features = ["user"] }

journal = { workspace = true }
rt = { path = "../../netdata-plugin/rt" }

allocative = { workspace = true, optional = true }

[dev-dependencies]
chrono = "0.4"
clap = { version = "4", features = ["derive"] }
tracing-subscriber = "0.3"

[lints]
workspace = true
