[package]
name = "journal-function"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[features]
allocative = ["dep:allocative"]


[dependencies]
async-stream = "0.3"
async-trait = { workspace = true }
futures = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
notify = { workspace = true }
foyer = { workspace = true }
parking_lot = { workspace = true, features = ["send_guard"] }

journal = { workspace = true }

allocative = { workspace = true, optional = true }

[lints]
workspace = true
