[package]
name = "fst-index"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
description = "Generic associative index backed by a finite state transducer"

[lints]
workspace = true

[dependencies]
fst = { workspace = true }

[dev-dependencies]
