[workspace]
resolver = "2"
members = [
    "error",
    "journal_file",
    "journal_log",
    "window_manager",
    "sigbus",
    "journal_registry",
]

[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.85"

[workspace.dependencies]
futures = "0.3"
anyhow = "1.0"
atoi = "2.0"
bytes = "1"
bytesize = "1.3"
bytesize-serde = "0.2"
chrono = { version = "0.4", features = ["serde"] }
hex = "0.4"
indexmap = "2.9"
libc = "0.2"
memmap2 = "0.9"
rand = "0.9"
regex = "1.10"
ruzstd = "0.8"
serde_json = "1.0"
serde_regex = "1.1.0"
serde = { version = "1.0", features = ["derive"] }
siphasher = "1.0"
static_assertions = "1.1"
tempfile = "3"
thiserror = "2"
tokio = { version = "1.45", features = ["rt-multi-thread", "process", "io-util"] }
tracing = "0.1"
twox-hash = { version = "2.1", default-features = false, features = ["std"] }
uuid = { version = "1.0", features = ["v4", "rng"] }
walkdir = "2"
zerocopy = { version = "0.9.0-alpha.0", features = ["derive"] }
bitflags = "2.9"
roaring = { version = "0.11.2", features = ["serde"] }
lz4 = "1.25"