[package]
name = "cli"
version.workspace = true
edition.workspace = true

[dependencies]
gorilla = { path = "../gorilla" }
error = { path = "../error" }
rand = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
tqdm = "0.7.0"

