[package]
name = "log-viewer-plugin"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[lib]
name = "log_viewer_plugin"
path = "src/lib.rs"

[[bin]]
name = "log-viewer-plugin"
path = "src/main.rs"

[dependencies]
async-trait = { workspace = true }

rt = { workspace = true }
netdata-plugin-error = { workspace = true }
netdata-plugin-protocol = { workspace = true }
netdata-plugin-schema = { workspace = true }
schemars = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
tracing-journald = { workspace = true }
tracing-opentelemetry = { workspace = true }
opentelemetry = { workspace = true }
opentelemetry_sdk = { workspace = true, features = ["rt-tokio"] }
opentelemetry-otlp = { workspace = true, features = ["grpc-tonic"] }
tokio = { workspace = true }
notify = { workspace = true }
thiserror = { workspace = true }
foyer = { workspace = true }

# Business logic
# journal-engine = { workspace = true }
# types = { path = "../types" }

journal-core = { workspace = true }
journal-index = { workspace = true }
journal-function = { workspace = true }
journal-registry = { workspace = true }
