[package]
name = "journal_file"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
error = { path = "../error" }
window_manager = { path = "../window_manager" }
ruzstd = { workspace = true }
siphasher = { workspace = true }
twox-hash = { workspace = true }
zerocopy = { workspace =  true }
hex = { workspace = true }
rand = { workspace = true }
allocative = "0.3.4"
roaring = { workspace = true }
lz4 = { workspace = true }
tracing = { workspace = true }
serde = { version = "1.0", features = ["derive"] }
uutils_term_grid = "0.7.0"
bincode = { version = "2.0.1", features = ["serde"] }

[dev-dependencies]
tempfile = { workspace = true }
