[workspace]
resolver = "2"
members = [
    "otel-plugin",
    "flatten_otel",
    "flog-otel",
]

[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.85"

[workspace.dependencies]
futures = "0.3"
anyhow = "1.0"
atty = "0.2"
bytes = "1"
bytesize = "1.3"
bytesize-serde = "0.2"
chrono = { version = "0.4", features = ["serde"] }
clap = { version = "4.5", features = ["derive", "env"] }
duct = "0.13"
humantime = "2.2"
humantime-serde = "1.1"
hyper-util = "0.1"
indexmap = "2.9"
opentelemetry = "0.27"
opentelemetry_sdk = { version = "0.27", features = ["rt-tokio", "logs"] }
opentelemetry-otlp = { version = "0.27", features = ["grpc-tonic", "logs"] }
opentelemetry-proto = "0.30"
phf_codegen = "0.12"
phf = { version = "0.12", default-features = false }
prost = "0.13"
prost-build = "0.13"
regex = "1.10"
serde_json = "1.0"
serde_regex = "1.1.0"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9.34"
tempfile = "3"
thiserror = "2"
tokio = { version = "1.45", features = ["rt-multi-thread", "process", "io-util"] }
tonic = "0.13"
tonic-build = "0.13"
tower = "0.5"
tracing = "0.1"
tracing-subscriber = "0.3"
uuid = { version = "1.0", features = ["v4", "rng"] }

journal_file = { path = "../netdata-journal/journal_file" }
journal_log = { path = "../netdata-journal/journal_log" }

flatten-serde-json = { git = "https://github.com/meilisearch/meilisearch", tag = "v1.22.1" }

[profile.release]
lto = true
opt-level = "z"
# strip = true
codegen-units = 1
