[package]
name = "journal_writer"
version.workspace = true
edition.workspace = true

[dependencies]
journal_file = { path = "../journal_file" }
error = { path = "../error" }
window_manager = { path = "../window_manager" }
memmap2 = { workspace = true }
zerocopy = { workspace = true }
rand = { workspace = true }

[dev-dependencies]
journal_reader = { path = "../journal_reader" }
tempfile = { workspace = true }

