[package]
name = "journal_forwarder"
version.workspace = true
edition.workspace = true

[dependencies]
error = { path = "../error" }
journal_file = { path = "../journal_file" }
journal_logger = { path = "../journal_logger" }
window_manager = { path = "../window_manager" }
memmap2 = { workspace = true }
rand = { workspace = true }
walkdir = { workspace = true }
