[package]
name = "journal_forwarder"
version.workspace = true
edition.workspace = true

[dependencies]
journal_file = { path = "../journal_file" }
journal_reader = { path = "../journal_reader" }
journal_logger = { path = "../journal_logger" }
error = { path = "../error" }
window_manager = { path = "../window_manager" }
memmap2 = { workspace = true }
rand = { workspace = true }
walkdir = { workspace = true }
