[package]
name = "tree-sitter-journal"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[[bin]]
name = "tree-sitter-journal"
path = "src/main.rs"

[dependencies]
journal-log-writer = { workspace = true }
journal-registry = { workspace = true }
tree-sitter = { workspace = true }
tree-sitter-rust = { workspace = true }
tree-sitter-c = { workspace = true }
walkdir = { workspace = true }
clap = { workspace = true }

[lints]
workspace = true
