[package]
name = "journal_registry"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
notify = "6.1"
parking_lot = "0.12"
thiserror = "1.0"
tracing = "0.1"
tracing-subscriber = "0.3"
walkdir = "2.4"
tokio = { version = "1.35", features = ["full"] }
crossbeam-channel = "0.5"
regex = { workspace = true }
journal_file = { path = "../journal_file" }
roaring = { workspace = true }
chrono = { workspace = true }
allocative = "0.3.4"
bitvec = "1.0.1"
lz4 = { workspace = true }
rayon = "1.11.0"
foyer = { path = "/home/vk/repos/crates/foyer/foyer", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rand = "0.8"
tempfile = { workspace = true }
anyhow = "1.0"

[[example]]
name = "basic_usage"
path = "examples/basic_usage.rs"

[[example]]
name = "basic_usage_with_cache"
path = "examples/basic_usage_with_cache.rs"

[[example]]
name = "histogram_viewer"
path = "examples/histogram_viewer.rs"

[[example]]
name = "filtered_histogram_viewer"
path = "examples/filtered_histogram_viewer.rs"

[[example]]
name = "file_index"
path = "examples/file_index.rs"
