[package]
name = "slotlog-producer"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
slotlog = { path = "../slotlog" }
tonic = { workspace = true }
tokio = { workspace = true }
rustc-hash = { workspace = true }
