[package]
name = "histogram-backend"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
axum = { workspace = true }
axum-tracing-opentelemetry = { workspace = true }

serde = { workspace = true  }
serde_json = { workspace = true }
rand = { workspace = true }
tokio = { workspace = true }
tower-http = { workspace = true, features = ["cors"] }

netdata-plugin-error = { workspace = true }
netdata-plugin-protocol = { workspace = true }
netdata-plugin-schema = { workspace = true }
journal_registry = { workspace = true }
types = { path = "../types" }
polars = { workspace = true }

tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter"] }
tracing-opentelemetry = { workspace = true }
tracing-futures = { workspace = true }
opentelemetry = { workspace = true }
opentelemetry_sdk = { workspace = true }
opentelemetry-otlp = { workspace = true, features = ["grpc-tonic"] }
