[package]
name = "histogram-backend"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
axum = "0.7"
serde = { workspace = true  }
serde_json = { workspace = true }
rand = "0.8"
tokio = { workspace = true }
tower-http = { version = "0.5", features = ["cors"] }

netdata-plugin-error = { workspace = true }
netdata-plugin-protocol = { workspace = true }
netdata-plugin-schema = { workspace = true }
journal_registry = { workspace = true }
