[package]
name = "histogram-backend"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
axum = "0.7"
tokio = { workspace = true }
serde = { workspace = true  }
serde_json = { workspace = true }
tower-http = { version = "0.5", features = ["cors"] }
rand = "0.8"
