[package]
name = "netdata-bridge"
version.workspace = true
edition.workspace = true

[dependencies]
tonic = { workspace = true }
tokio = { workspace = true }
tokio-stream = { workspace = true }
hyper-util = { workspace = true }
tower = { workspace = true }
prost = { workspace = true }

[build-dependencies]
tonic-build = { workspace = true }
prost-build = { workspace = true }