[package]
name = "journal_reader"
version.workspace = true
edition.workspace = true

[dependencies]
window_manager = { path = "../window_manager" }
journal_file = { path = "../journal_file" }
error = { path = "../error" }
