[package]
name = "schema-generator"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[[bin]]
name = "schema-generator"
path = "src/main.rs"

[dependencies]
netdata-schema = { path = "../netdata-schema" }
schemars = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }