[[language]]
name = "rust"
[language-server.rust-analyzer]
timeout = 240

[language-server.rust-analyzer.config.check]
command = "clippy"

[language-server.rust-analyzer.config.cargo]
features = [ "allocative" ]


