[package]
name = "main"
version.workspace = true
edition.workspace = true

[dependencies]
journal_file = { path = "../journal_file" }
journal_reader = { path = "../journal_reader" }
journal_logger = { path = "../journal_logger" }
zerocopy = { workspace = true }
error = { path = "../error" }
window_manager = { path = "../window_manager" }
chrono = "0.4"
systemd = { workspace = true }
rand = { workspace = true }
